image: openjdk:11-jdk
stages:
  - compile
  - test

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

compile:
  stage: compile
  script:
    - chmod +x ./gradlew
    - ./gradlew assemble

test:
  stage: test
  script:
    - chmod +x ./gradlew
    - ./gradlew test --stacktrace

code_style:
  stage: test
  script:
    - chmod +x ./gradlew
    - ./gradlew ktlintCheck
  artifacts:
    paths:
      - build/ktlint.xml
    expire_in: 1 week
  allow_failure: true
