version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    ports:
      - 8083:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: OhlczFA#gs9B

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: OhlczFA#gs9B
      ME_CONFIG_MONGODB_URL: mongodb://root:OhlczFA#gs9B@mongo:27017/
  
  office_backend:
    depends_on:
        - mongo
        - mongo-express
    build: office_backend
    ports:
      - 8082:8082

  cloud_backend:
    build: cloud_backend
    ports:
      - 8084:8084